### ISSUE TITLE
Possibility to set the number of workers

### ISSUE THREAD

**Issue by leonfs** [ovhemert/gatsby-plugin-iltorb#1]
Hi,

First of all, thank you for maintaining the plugin.

While setting it up, I noticed that the plugin has a problem with certain CI environments. The `worker-farm` library used to create a pool of workes relies on `require('os').cpus()`. This is known to not provide a reliable mechanism to determine the number of virtual CPUs on containerised environments.

Ideally, and knowing this is a gatsby plugin, to rely on the same environment variable gatsby uses to set the number of CPUs by using `GATSBY_CPU_COUNT` variable.

Thanks,
Leo

**Comment by ovhemert** [comment]
Thanks for the suggestion. It would be great to rely on `GATSBY_CPU_COUNT` first if the value is available. Would you mind sending a PR to add it as an [option](https://www.npmjs.com/package/worker-farm#options) to the worker farm, and fallback on the default if ENV var is not available?
